### ISSUE TITLE
Use gormlite

### ISSUE THREAD

**Issue by ncruces** [reeflective/team#12]
For your `wasmsqlite` package, you might want to use:
[`github.com/ncruces/go-sqlite3/gormlite`](https://pkg.go.dev/github.com/ncruces/go-sqlite3/gormlite)

**Comment by maxlandon** [comment]
Sorry, I had not seen this.
Thanks a lot for the suggestion !

**Comment by maxlandon** [comment]
@ncruces if I may ask, how did you learn about this repository ?

**Comment by ncruces** [comment]
It showed up here:
https://github.com/ncruces/go-sqlite3/network/dependents?package_id=UGFja2FnZS0zNTI3Mzg4NDQx

Since I don't have lots of users, I often have a look to guide development.

I added GORM because of this (and because it has a bunch of tests I can run).

**Comment by maxlandon** [comment]
Oh ok that's great, thank you very much for the attention !
Will update with your suggestion.

Cheers

**Comment by maxlandon** [comment]
Hello @ncruces ! Finally getting to update this, after doing so, I'm not entirely sure if I'm not doing some useless anonymous calls here. Sorry for asking this, but I don't have to look at that every day so I'm no specialist...

In any case, the current compiles and passes all my CI for all platforms, so I don't really have an issue. Just a doubt.

What I would be grateful for you doing is to check those 4 -very very short- files where I have to import your libs.
Could you be kind enough to tell me if there useless anonymous calls ? 
In https://github.com/reeflective/team/tree/main/internal/db:
- sql-cgo.go
- sql-go.go
- sql-wasm.go
- sql.go

If one those files even appeared useless by now, I would very much appreciate you telling me this too !

Thanks a lot for the initial reach anyway.

**Comment by ncruces** [comment]
OK, I'm not sure I fully understand your build tags `wasm_sqlite` and `cgo_sqlite`. But…

Assuming that with `cgo_sqlite` you want the most popular SQLite CGO [driver](https://github.com/mattn/go-sqlite3), the `sql-cgo.go` file doesn't need to import any of my packages. Importing the default GORM [driver](https://gorm.io/driver/sqlite) is all you need.

I'm not sure I understand the intent between the other two implementations, but `sql-go.go` is pretty much how `gormlite` (the GORM driver to my WASM SQLite wrapper) is meant to be used. I don't understand what `sql-wasm.go` is about, TBH.

**Comment by maxlandon** [comment]
Okay I'm taking note of this.
For info I've just been using a security tool's codebase for database backend, and like many other software they had some issues running databases without CGO for years, so they resorted to some alternative methods.

I'm not sure I understand them well either, but I'm sure they'll be removed as soon as its clear they are not needed (especially the `wasm` directory).

Thanks for the help anyway, will remove those imports ASAP !

**Comment by ncruces** [comment]
Ah, OK.

So there's [another](https://gitlab.com/cznic/sqlite), more mature, CGO free, SQLite port, which is based on transpiling C to Go, and a GORM [driver](https://github.com/glebarez/sqlite) based on it.

[These](https://github.com/BishopFox/sliver) guys (I'm assuming it's them) tried to port the CGO free driver to use my implementation instead.

I don't use GORM myself, but it has a bunch of unit tests which helps be have more confidence in my own SQLite port, so I decided to do a GORM driver myself. Hence `gormlite`.

TBH, if you're looking for maturity and performance, you may be better of with these other drivers (the default CGO one, and the transpiled one).

Going forward it's likely the WASM runtime I use, and of which I'm a community maintainer ([wazero](https://wazero.io/)) will improve, which may make my driver more competitive (esp. performance).

**Comment by maxlandon** [comment]
Haha yup these guys.
The very repository on which we are speaking here is a refactor of some of their code, for domain-agnostic usage.

So for now I do not personally have concerns for performance over a default, obvious and reliable database.
And given the 0 user base of this current repo, not many cries you'll see.

I'm leaving this open anyway as I'd prefer to get a grasp of that before committing (for my own education).
I appreciate the additional hints you gave, thanks a lot.

**Comment by maxlandon** [comment]
Fixed in #17 , thanks a lot @ncruces for your kind help !
